### ISSUE TITLE
Can not use Jmeter action with java11

### ISSUE THREAD

**Issue by SeleniumTestAB** [rbhadti94/apache-jmeter-action#11]
During development of small test project with github actions it was observed, that on the step with Jmeter action, the workflow fails.

adding picture

![obraz](https://user-images.githubusercontent.com/38245002/101289843-20b73d80-37ff-11eb-9c77-13c03f021d2c.png)

**Comment by rbhadti94** [comment]
Hi @SeleniumTestAB ,

Thanks for raising this. Can you provide more details as to how you're running this?

1. What command is being run?
2. What version of the action are you using? This was recently upgraded to v0.3.0 - so may be worth trying v0.2.0 and seeing if it works?

**Comment by SeleniumTestAB** [comment]
Hi @rbhadti94 

So here is my workflow file
https://github.com/SeleniumTestAB/bitpanda-tasks-solution/actions/runs/404355771/workflow

here is command that i use 
`    - name: Run Load Task with JMeter
      uses: rbhadti94/apache-jmeter-action@v0.3.0
      with:
        testFilePath: ${{ env.JMETER_TEST_PLAN_PATH }}
        outputReportsFolder: jmeter-reports/
      continue-on-error: true`

that's for 1 question. For second one, I tested version 0.2.0 and 0.3.0 and both gave me the same error

**Comment by rbhadti94** [comment]
Thanks, let me take a look at this. I can see you're loading java-11 at the beginning of the workflow but this shouldn't have an impact.

**Comment by rbhadti94** [comment]
Hi @SeleniumTestAB - Please try with v0.3.1 - I've merged in a PR for this issue
