### ISSUE TITLE
running multiple JMeter scripts in GitHUB Actions

### ISSUE THREAD

**Issue by sebiboga** [rbhadti94/apache-jmeter-action#21]
Using this action we can run one jmx file

1. Can you please enhance it to be able to add multiple files?
2. Can you please enhance it to be able to run all jmx files from a specific folder (from the repository)

**Comment by rbhadti94** [comment]
Hi @sebiboga , can you paste the jmeter command that would allow this. To my knowledge, the `jmeter` CLI tool only takes in a single JMX file.

**Comment by sebiboga** [comment]
yeah. I already posted on dev.to how to run multiple jmx files with Github Actions.
The secret is to use a for in linux so you pass to jmeter -n -t all files one by one...

See my post in dev.to ... (not using docker...)

**Comment by sebiboga** [comment]
https://dev.to/sebiboga/execute-all-jmeter-files-with-github-actions-3n56

**Comment by rbhadti94** [comment]
Thanks @sebiboga - Will have something in place soon. Think I found a way to do this.

**Comment by rbhadti94** [comment]
Should be completed and merged in now 👍

**Comment by sebiboga** [comment]
@rbhadti94 can you please update the documentation on how we specify multiple files using the plugin?
- current documentation explain how to run just one jmx file

**Comment by rbhadti94** [comment]
Hi @sebiboga, please can you verify now?

**Comment by sebiboga** [comment]
sure, just don't know how to specify multiple files. where can I find an example?

**Comment by rbhadti94** [comment]
I've merged in the README.md to the main branch. It should have updated examples.

**Comment by sebiboga** [comment]
@rbhadti94 got it. just read it. so when we specify the folder, all jmx files from that folder will be executed. I'll retest it and be back with results. thanks.

**Comment by sebiboga** [comment]
@rbhadti94 indeed it works when defining a folder.
![image](https://user-images.githubusercontent.com/41440889/150539302-9a42dfa8-3b24-4399-9993-a3ea49720138.png)

here is the section from yml file:
![image](https://user-images.githubusercontent.com/41440889/150539411-19ffee70-0291-463b-a666-36e24755876f.png)

GREAT JOB!!!
