### ISSUE TITLE
Run multiple files in one folder

### ISSUE THREAD

**Issue by xiaoyu-wu566** [rbhadti94/apache-jmeter-action#25]
I have a nested folder like testJmeter/tests, and there are multiple test cases in it. But when I use 
uses: rbhadti94/apache-jmeter-action@v0.5.0
with: 
      testFilePath: testJmeter/tests/
      outputReportsFolder: reports/
It will failed with An error occurred: The file /github/workspace/tests/*.jmx doesn't exist or can't be opened and I checked the log. It says Using Test File Path testJmeter/tests (correct), Running test with tests/*.jmx (I think something wrong here as you use BASEFILE_PATH=$(basename $TESTFILE_PATH), you remove the prefix path here). 
Is this the issue or I did something wrong? Could you please help me with it. Thanks

**Comment by rbhadti94** [comment]
Hey @xiaoyu-wu566,

I see where the issue is - https://github.com/rbhadti94/apache-jmeter-action/blob/master/entrypoint.sh#L38

Will get a fix in this week. Thanks for pointing it out. Basically I have to loop recursively through folders rather than the top level.

**Comment by xiaoyu-wu566** [comment]
Hi Ravindra, 
Thanks very much! I forked you code and just changed BASEFILE_PATH to TESTFILE_PATH in the for loop. Then everything looks correct.

**Comment by rbhadti94** [comment]
@xiaoyu-wu566 - v0.6.0 should contain this feature now.
